# Generated by Django 3.2.4 on 2021-06-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер заработной платы')),
                ('salary_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выплаченная зарплата')),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1, verbose_name='Уровень иерархии')),
                ('chief', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='employees.employee', verbose_name='Начальник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['fio'],
            },
        ),
    ]
